package com.streamvault.data.local.dao

/**
 * Resolves the local `series.id` for an incoming summary/category row so that a
 * summary re-sync updates the existing row in place instead of re-creating it with
 * a new autogenerated id.
 *
 * Episodes are linked to a series by its local row id ([EpisodeEntity.seriesId]).
 * If a re-sync re-inserts a series under a new id, the old episodes are orphaned and
 * later purged by daily maintenance, leaving series details with no seasons/episodes.
 *
 * Matching order:
 *  1. by the provider's remote key (`provider_series_id` when present, else `series_id`);
 *  2. by the stable numeric `series_id` identity, which survives a remote-key
 *     representation change (e.g. the provider starting/stopping sending
 *     `provider_series_id`). `series_id == 0` is not a stable identity and is ignored.
 *
 * Returns `0` for a genuinely new row so Room autogenerates its id.
 */
internal fun resolveExistingSeriesId(
    remoteKey: String,
    seriesId: Long,
    existingByRemoteKey: Map<String, Long>,
    existingBySeriesId: Map<Long, Long>
): Long =
    existingByRemoteKey[remoteKey]
        ?: seriesId.takeIf { it > 0L }?.let { existingBySeriesId[it] }
        ?: 0L
