package com.streamvault.data.local

import android.content.Context
import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.google.common.truth.Truth.assertThat
import com.streamvault.data.local.dao.EpisodeDao
import com.streamvault.data.local.dao.SeriesDao
import com.streamvault.data.local.entity.EpisodeEntity
import com.streamvault.data.local.entity.SeriesEntity
import kotlinx.coroutines.test.runTest
import org.junit.After
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

/**
 * Regression coverage for series episodes disappearing after a summary re-sync.
 *
 * Episodes are linked to a series by its local row id. When a category/summary
 * re-sync re-inserts a series whose remote-key representation changed (e.g. the
 * provider stops sending `provider_series_id`, so the key flips from the string
 * id to the numeric `series_id`), the id remap must still resolve the existing
 * row by its stable `(provider_id, series_id)` identity. Otherwise the row is
 * re-created with a new autogenerated id and its episodes are orphaned (and later
 * purged by daily maintenance), leaving series details with no seasons/episodes.
 */
@RunWith(AndroidJUnit4::class)
class SeriesEpisodeIdStabilityTest {
    private lateinit var db: StreamVaultDatabase
    private lateinit var seriesDao: SeriesDao
    private lateinit var episodeDao: EpisodeDao

    @Before
    fun createDb() {
        val context = ApplicationProvider.getApplicationContext<Context>()
        db = Room.inMemoryDatabaseBuilder(context, StreamVaultDatabase::class.java).build()
        seriesDao = db.seriesDao()
        episodeDao = db.episodeDao()
    }

    @After
    fun closeDb() {
        db.close()
    }

    @Test
    fun upsertCategoryPage_keepsSeriesIdAndEpisodes_whenProviderSeriesIdRepresentationChanges() = runTest {
        // Existing hydrated series with provider_series_id populated -> remoteKey = "s100".
        seriesDao.insertAll(
            listOf(
                SeriesEntity(
                    seriesId = 100L,
                    providerSeriesId = "s100",
                    name = "Show",
                    providerId = 5L,
                    categoryId = 7L
                )
            )
        )
        val original = requireNotNull(seriesDao.getBySeriesId(5L, 100L))
        episodeDao.insertAll(
            listOf(
                EpisodeEntity(
                    episodeId = 7001L,
                    title = "Pilot",
                    episodeNumber = 1,
                    seasonNumber = 1,
                    seriesId = original.id,
                    providerId = 5L
                )
            )
        )

        // Same (provider, series_id) re-synced without provider_series_id -> remoteKey = "100".
        seriesDao.upsertCategoryPage(
            5L,
            listOf(
                SeriesEntity(
                    seriesId = 100L,
                    providerSeriesId = null,
                    name = "Show",
                    providerId = 5L,
                    categoryId = 7L
                )
            )
        )

        val after = requireNotNull(seriesDao.getBySeriesId(5L, 100L))
        // The local row id must stay stable so episodes remain linked to the current row.
        assertThat(after.id).isEqualTo(original.id)
        assertThat(episodeDao.getBySeriesSync(after.id)).isNotEmpty()
    }
}
